# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.py'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 833)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, -1, 1081, 801))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.beginAction = QtWidgets.QPushButton(self.tab)
        self.beginAction.setGeometry(QtCore.QRect(50, 500, 81, 23))
        self.beginAction.setObjectName("beginAction")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 560, 81, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.cancelTest = QtWidgets.QPushButton(self.tab)
        self.cancelTest.setGeometry(QtCore.QRect(50, 620, 81, 23))
        self.cancelTest.setObjectName("cancelTest")
        self.testType = QtWidgets.QComboBox(self.tab)
        self.testType.setGeometry(QtCore.QRect(130, 140, 111, 22))
        self.testType.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.testType.setObjectName("testType")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(50, 80, 71, 21))
        self.label_17.setObjectName("label_17")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(50, 110, 71, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(50, 140, 71, 21))
        self.label_24.setObjectName("label_24")
        self.testTemp = QtWidgets.QComboBox(self.tab)
        self.testTemp.setGeometry(QtCore.QRect(130, 170, 111, 22))
        self.testTemp.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.testTemp.setObjectName("testTemp")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(50, 170, 71, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(50, 200, 71, 21))
        self.label_26.setObjectName("label_26")
        self.chipName = QtWidgets.QLineEdit(self.tab)
        self.chipName.setGeometry(QtCore.QRect(130, 80, 111, 20))
        self.chipName.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.chipName.setObjectName("chipName")
        self.chipNum = QtWidgets.QLineEdit(self.tab)
        self.chipNum.setGeometry(QtCore.QRect(130, 110, 111, 20))
        self.chipNum.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.chipNum.setObjectName("chipNum")
        self.testerNum = QtWidgets.QLineEdit(self.tab)
        self.testerNum.setGeometry(QtCore.QRect(130, 200, 111, 20))
        self.testerNum.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.testerNum.setObjectName("testerNum")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(50, 230, 71, 21))
        self.label_27.setObjectName("label_27")
        self.testDate = QtWidgets.QDateEdit(self.tab)
        self.testDate.setGeometry(QtCore.QRect(130, 230, 111, 22))
        self.testDate.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.testDate.setObjectName("testDate")
        self.debugView = QtWidgets.QPlainTextEdit(self.tab)
        self.debugView.setGeometry(QtCore.QRect(340, 50, 641, 601))
        self.debugView.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.debugView.setObjectName("debugView")
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(230, 690, 521, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(28)
        font.setUnderline(True)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(180, 680, 61, 51))
        self.label_35.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap(":/img/img2.png"))
        self.label_35.setObjectName("label_35")
        self.successDisplay = QtWidgets.QLabel(self.tab)
        self.successDisplay.setGeometry(QtCore.QRect(1020, 50, 31, 31))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(20)
        self.successDisplay.setFont(font)
        self.successDisplay.setStyleSheet("color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(0, 255, 78, 255));")
        self.successDisplay.setObjectName("successDisplay")
        self.errDisplay = QtWidgets.QLabel(self.tab)
        self.errDisplay.setGeometry(QtCore.QRect(1020, 40, 31, 41))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(22)
        self.errDisplay.setFont(font)
        self.errDisplay.setStyleSheet("color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 0, 0, 255));")
        self.errDisplay.setObjectName("errDisplay")
        self.stateDisplay = QtWidgets.QLabel(self.tab)
        self.stateDisplay.setGeometry(QtCore.QRect(750, 50, 51, 31))
        self.stateDisplay.setText("")
        self.stateDisplay.setObjectName("stateDisplay")
        self.dataLocation = QtWidgets.QComboBox(self.tab)
        self.dataLocation.setGeometry(QtCore.QRect(130, 260, 111, 22))
        self.dataLocation.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.dataLocation.setObjectName("dataLocation")
        self.label_70 = QtWidgets.QLabel(self.tab)
        self.label_70.setGeometry(QtCore.QRect(50, 260, 71, 21))
        self.label_70.setObjectName("label_70")
        self.fileDir = QtWidgets.QLineEdit(self.tab)
        self.fileDir.setGeometry(QtCore.QRect(50, 290, 121, 20))
        self.fileDir.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.fileDir.setObjectName("fileDir")
        self.selectTxtFile = QtWidgets.QPushButton(self.tab)
        self.selectTxtFile.setGeometry(QtCore.QRect(180, 290, 41, 23))
        self.selectTxtFile.setObjectName("selectTxtFile")
        self.pltBtn = QtWidgets.QPushButton(self.tab)
        self.pltBtn.setGeometry(QtCore.QRect(230, 290, 41, 23))
        self.pltBtn.setObjectName("pltBtn")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(760, 710, 72, 15))
        self.label.setObjectName("label")
        self.label_74 = QtWidgets.QLabel(self.tab)
        self.label_74.setGeometry(QtCore.QRect(50, 50, 71, 21))
        self.label_74.setObjectName("label_74")
        self.iniFileDir = QtWidgets.QLineEdit(self.tab)
        self.iniFileDir.setGeometry(QtCore.QRect(130, 51, 111, 20))
        self.iniFileDir.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.iniFileDir.setObjectName("iniFileDir")
        self.selectDirBT = QtWidgets.QPushButton(self.tab)
        self.selectDirBT.setGeometry(QtCore.QRect(250, 52, 41, 21))
        self.selectDirBT.setObjectName("selectDirBT")
        self.uartComBox = QtWidgets.QComboBox(self.tab)
        self.uartComBox.setGeometry(QtCore.QRect(50, 340, 101, 22))
        self.uartComBox.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.uartComBox.setObjectName("uartComBox")
        self.uartComFreshBT = QtWidgets.QPushButton(self.tab)
        self.uartComFreshBT.setGeometry(QtCore.QRect(160, 340, 81, 23))
        self.uartComFreshBT.setObjectName("uartComFreshBT")
        self.openCurrUartBT = QtWidgets.QPushButton(self.tab)
        self.openCurrUartBT.setGeometry(QtCore.QRect(250, 340, 81, 23))
        self.openCurrUartBT.setObjectName("openCurrUartBT")
        self.clearDebugBT = QtWidgets.QPushButton(self.tab)
        self.clearDebugBT.setGeometry(QtCore.QRect(990, 630, 71, 23))
        self.clearDebugBT.setObjectName("clearDebugBT")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.S_DataDev = QtWidgets.QComboBox(self.tab_3)
        self.S_DataDev.setGeometry(QtCore.QRect(490, 30, 201, 22))
        self.S_DataDev.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.S_DataDev.setObjectName("S_DataDev")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(410, 30, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(410, 210, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.S_DataCheckBox = QtWidgets.QCheckBox(self.tab_3)
        self.S_DataCheckBox.setGeometry(QtCore.QRect(180, 30, 16, 16))
        self.S_DataCheckBox.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.S_DataCheckBox.setText("")
        self.S_DataCheckBox.setObjectName("S_DataCheckBox")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(40, 25, 131, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.S_DataDevRefresh = QtWidgets.QPushButton(self.tab_3)
        self.S_DataDevRefresh.setGeometry(QtCore.QRect(720, 20, 75, 23))
        self.S_DataDevRefresh.setObjectName("S_DataDevRefresh")
        self.S_DataConConfirmAct = QtWidgets.QPushButton(self.tab_3)
        self.S_DataConConfirmAct.setGeometry(QtCore.QRect(720, 50, 75, 23))
        self.S_DataConConfirmAct.setObjectName("S_DataConConfirmAct")
        self.S_DataSetConfirmAct = QtWidgets.QPushButton(self.tab_3)
        self.S_DataSetConfirmAct.setGeometry(QtCore.QRect(730, 450, 75, 23))
        self.S_DataSetConfirmAct.setObjectName("S_DataSetConfirmAct")
        self.S_DataComOpen = QtWidgets.QPushButton(self.tab_3)
        self.S_DataComOpen.setGeometry(QtCore.QRect(200, 120, 71, 23))
        self.S_DataComOpen.setObjectName("S_DataComOpen")
        self.S_DataComBox = QtWidgets.QComboBox(self.tab_3)
        self.S_DataComBox.setGeometry(QtCore.QRect(110, 90, 81, 22))
        self.S_DataComBox.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.S_DataComBox.setObjectName("S_DataComBox")
        self.S_DataComFresh = QtWidgets.QPushButton(self.tab_3)
        self.S_DataComFresh.setGeometry(QtCore.QRect(200, 90, 71, 23))
        self.S_DataComFresh.setObjectName("S_DataComFresh")
        self.S_DataConComander = QtWidgets.QTextEdit(self.tab_3)
        self.S_DataConComander.setGeometry(QtCore.QRect(120, 210, 241, 251))
        self.S_DataConComander.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.S_DataConComander.setObjectName("S_DataConComander")
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(50, 210, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(170, 490, 521, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(28)
        font.setUnderline(True)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(120, 480, 61, 51))
        self.label_33.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap(":/img/img2.png"))
        self.label_33.setObjectName("label_33")
        self.S_DataSetRefreshAct = QtWidgets.QPushButton(self.tab_3)
        self.S_DataSetRefreshAct.setGeometry(QtCore.QRect(730, 420, 75, 23))
        self.S_DataSetRefreshAct.setObjectName("S_DataSetRefreshAct")
        self.powerInData = QtWidgets.QLineEdit(self.tab_3)
        self.powerInData.setGeometry(QtCore.QRect(490, 210, 201, 20))
        self.powerInData.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.powerInData.setObjectName("powerInData")
        self.startFreqData = QtWidgets.QLineEdit(self.tab_3)
        self.startFreqData.setGeometry(QtCore.QRect(490, 250, 201, 20))
        self.startFreqData.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.startFreqData.setText("")
        self.startFreqData.setObjectName("startFreqData")
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        self.label_36.setGeometry(QtCore.QRect(410, 250, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_3)
        self.label_37.setGeometry(QtCore.QRect(410, 290, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.stopFreqData = QtWidgets.QLineEdit(self.tab_3)
        self.stopFreqData.setGeometry(QtCore.QRect(490, 290, 201, 20))
        self.stopFreqData.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.stopFreqData.setText("")
        self.stopFreqData.setObjectName("stopFreqData")
        self.label_53 = QtWidgets.QLabel(self.tab_3)
        self.label_53.setGeometry(QtCore.QRect(700, 210, 111, 21))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_3)
        self.label_54.setGeometry(QtCore.QRect(700, 250, 111, 21))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_3)
        self.label_55.setGeometry(QtCore.QRect(700, 290, 111, 21))
        self.label_55.setObjectName("label_55")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.P1Dev = QtWidgets.QComboBox(self.tab_4)
        self.P1Dev.setGeometry(QtCore.QRect(490, 30, 201, 22))
        self.P1Dev.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.P1Dev.setObjectName("P1Dev")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(410, 30, 91, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(410, 215, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.P1TestCondition = QtWidgets.QTextEdit(self.tab_4)
        self.P1TestCondition.setGeometry(QtCore.QRect(490, 215, 201, 121))
        self.P1TestCondition.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.P1TestCondition.setObjectName("P1TestCondition")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(410, 80, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(410, 110, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.P1AverData = QtWidgets.QLineEdit(self.tab_4)
        self.P1AverData.setGeometry(QtCore.QRect(490, 80, 201, 20))
        self.P1AverData.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.P1AverData.setObjectName("P1AverData")
        self.P1PowerStopData = QtWidgets.QLineEdit(self.tab_4)
        self.P1PowerStopData.setGeometry(QtCore.QRect(490, 110, 201, 20))
        self.P1PowerStopData.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.P1PowerStopData.setObjectName("P1PowerStopData")
        self.P1ComOpen = QtWidgets.QPushButton(self.tab_4)
        self.P1ComOpen.setGeometry(QtCore.QRect(200, 120, 71, 23))
        self.P1ComOpen.setObjectName("P1ComOpen")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(40, 25, 131, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.P1ConComander = QtWidgets.QTextEdit(self.tab_4)
        self.P1ConComander.setGeometry(QtCore.QRect(120, 210, 241, 251))
        self.P1ConComander.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.P1ConComander.setObjectName("P1ConComander")
        self.P1CheckBox = QtWidgets.QCheckBox(self.tab_4)
        self.P1CheckBox.setGeometry(QtCore.QRect(180, 30, 16, 16))
        self.P1CheckBox.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.P1CheckBox.setText("")
        self.P1CheckBox.setObjectName("P1CheckBox")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(50, 210, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.P1ComFresh = QtWidgets.QPushButton(self.tab_4)
        self.P1ComFresh.setGeometry(QtCore.QRect(200, 90, 71, 23))
        self.P1ComFresh.setObjectName("P1ComFresh")
        self.P1ComBox = QtWidgets.QComboBox(self.tab_4)
        self.P1ComBox.setGeometry(QtCore.QRect(110, 90, 81, 22))
        self.P1ComBox.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.P1ComBox.setObjectName("P1ComBox")
        self.P1ConConfirmAct = QtWidgets.QPushButton(self.tab_4)
        self.P1ConConfirmAct.setGeometry(QtCore.QRect(720, 50, 75, 23))
        self.P1ConConfirmAct.setObjectName("P1ConConfirmAct")
        self.P1DevRefresh = QtWidgets.QPushButton(self.tab_4)
        self.P1DevRefresh.setGeometry(QtCore.QRect(720, 20, 75, 23))
        self.P1DevRefresh.setObjectName("P1DevRefresh")
        self.P1SetConfirmAct = QtWidgets.QPushButton(self.tab_4)
        self.P1SetConfirmAct.setGeometry(QtCore.QRect(730, 450, 75, 23))
        self.P1SetConfirmAct.setObjectName("P1SetConfirmAct")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(170, 490, 521, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(28)
        font.setUnderline(True)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        self.label_31.setGeometry(QtCore.QRect(120, 480, 61, 51))
        self.label_31.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap(":/img/img2.png"))
        self.label_31.setObjectName("label_31")
        self.P1SetRefreshAct = QtWidgets.QPushButton(self.tab_4)
        self.P1SetRefreshAct.setGeometry(QtCore.QRect(730, 420, 75, 23))
        self.P1SetRefreshAct.setObjectName("P1SetRefreshAct")
        self.label_58 = QtWidgets.QLabel(self.tab_4)
        self.label_58.setGeometry(QtCore.QRect(710, 110, 111, 21))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_4)
        self.label_59.setGeometry(QtCore.QRect(710, 80, 111, 21))
        self.label_59.setObjectName("label_59")
        self.label_44 = QtWidgets.QLabel(self.tab_4)
        self.label_44.setGeometry(QtCore.QRect(410, 180, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_50 = QtWidgets.QLabel(self.tab_4)
        self.label_50.setGeometry(QtCore.QRect(410, 150, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.P1HighTh = QtWidgets.QLineEdit(self.tab_4)
        self.P1HighTh.setGeometry(QtCore.QRect(490, 150, 201, 20))
        self.P1HighTh.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.P1HighTh.setObjectName("P1HighTh")
        self.P1LowTh = QtWidgets.QLineEdit(self.tab_4)
        self.P1LowTh.setGeometry(QtCore.QRect(490, 180, 201, 20))
        self.P1LowTh.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.P1LowTh.setObjectName("P1LowTh")
        self.label_61 = QtWidgets.QLabel(self.tab_4)
        self.label_61.setGeometry(QtCore.QRect(710, 150, 111, 21))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.tab_4)
        self.label_62.setGeometry(QtCore.QRect(710, 180, 111, 21))
        self.label_62.setObjectName("label_62")
        self.P1LossValue = QtWidgets.QTextEdit(self.tab_4)
        self.P1LossValue.setGeometry(QtCore.QRect(490, 350, 201, 121))
        self.P1LossValue.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.P1LossValue.setObjectName("P1LossValue")
        self.label_73 = QtWidgets.QLabel(self.tab_4)
        self.label_73.setGeometry(QtCore.QRect(410, 360, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.OIP3FreqDev = QtWidgets.QComboBox(self.tab_2)
        self.OIP3FreqDev.setGeometry(QtCore.QRect(510, 30, 181, 22))
        self.OIP3FreqDev.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.OIP3FreqDev.setObjectName("OIP3FreqDev")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(410, 30, 101, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(410, 80, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.OIP3SignalDev = QtWidgets.QComboBox(self.tab_2)
        self.OIP3SignalDev.setGeometry(QtCore.QRect(510, 80, 181, 22))
        self.OIP3SignalDev.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.OIP3SignalDev.setObjectName("OIP3SignalDev")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(410, 310, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.OIP3TestCondition = QtWidgets.QTextEdit(self.tab_2)
        self.OIP3TestCondition.setGeometry(QtCore.QRect(510, 300, 211, 81))
        self.OIP3TestCondition.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.OIP3TestCondition.setObjectName("OIP3TestCondition")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(410, 430, 91, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.OIP3LossValue = QtWidgets.QTextEdit(self.tab_2)
        self.OIP3LossValue.setGeometry(QtCore.QRect(510, 400, 211, 81))
        self.OIP3LossValue.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.OIP3LossValue.setObjectName("OIP3LossValue")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(410, 190, 91, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(410, 160, 91, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.sweepBW = QtWidgets.QLineEdit(self.tab_2)
        self.sweepBW.setGeometry(QtCore.QRect(510, 160, 171, 20))
        self.sweepBW.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.sweepBW.setObjectName("sweepBW")
        self.signalProtect = QtWidgets.QLineEdit(self.tab_2)
        self.signalProtect.setGeometry(QtCore.QRect(510, 190, 171, 20))
        self.signalProtect.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.signalProtect.setObjectName("signalProtect")
        self.OIP3CheckBox = QtWidgets.QCheckBox(self.tab_2)
        self.OIP3CheckBox.setGeometry(QtCore.QRect(180, 30, 16, 16))
        self.OIP3CheckBox.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(241, 241, 162, 255));")
        self.OIP3CheckBox.setText("")
        self.OIP3CheckBox.setObjectName("OIP3CheckBox")
        self.OIP3ComOpen = QtWidgets.QPushButton(self.tab_2)
        self.OIP3ComOpen.setGeometry(QtCore.QRect(200, 120, 71, 23))
        self.OIP3ComOpen.setObjectName("OIP3ComOpen")
        self.OIP3ComBox = QtWidgets.QComboBox(self.tab_2)
        self.OIP3ComBox.setGeometry(QtCore.QRect(110, 90, 81, 22))
        self.OIP3ComBox.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.OIP3ComBox.setObjectName("OIP3ComBox")
        self.OIP3ComFresh = QtWidgets.QPushButton(self.tab_2)
        self.OIP3ComFresh.setGeometry(QtCore.QRect(200, 90, 71, 23))
        self.OIP3ComFresh.setObjectName("OIP3ComFresh")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(40, 25, 131, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.OIP3ConComander = QtWidgets.QTextEdit(self.tab_2)
        self.OIP3ConComander.setGeometry(QtCore.QRect(120, 210, 241, 251))
        self.OIP3ConComander.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.OIP3ConComander.setObjectName("OIP3ConComander")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(50, 210, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.conConfirmAct1 = QtWidgets.QPushButton(self.tab_2)
        self.conConfirmAct1.setGeometry(QtCore.QRect(720, 50, 75, 23))
        self.conConfirmAct1.setObjectName("conConfirmAct1")
        self.OIP3DevRefresh = QtWidgets.QPushButton(self.tab_2)
        self.OIP3DevRefresh.setGeometry(QtCore.QRect(720, 20, 75, 23))
        self.OIP3DevRefresh.setObjectName("OIP3DevRefresh")
        self.conConfirmAct2 = QtWidgets.QPushButton(self.tab_2)
        self.conConfirmAct2.setGeometry(QtCore.QRect(720, 80, 75, 23))
        self.conConfirmAct2.setObjectName("conConfirmAct2")
        self.setConfirmAct = QtWidgets.QPushButton(self.tab_2)
        self.setConfirmAct.setGeometry(QtCore.QRect(730, 450, 75, 23))
        self.setConfirmAct.setObjectName("setConfirmAct")
        self.setRefreshAct = QtWidgets.QPushButton(self.tab_2)
        self.setRefreshAct.setGeometry(QtCore.QRect(730, 420, 75, 23))
        self.setRefreshAct.setObjectName("setRefreshAct")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(120, 480, 61, 51))
        self.label_19.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/img/img2.png"))
        self.label_19.setObjectName("label_19")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(170, 490, 521, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(28)
        font.setUnderline(True)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_29.setObjectName("label_29")
        self.label_56 = QtWidgets.QLabel(self.tab_2)
        self.label_56.setGeometry(QtCore.QRect(690, 160, 111, 21))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_2)
        self.label_57.setGeometry(QtCore.QRect(690, 190, 111, 21))
        self.label_57.setObjectName("label_57")
        self.OIP3LowTh = QtWidgets.QLineEdit(self.tab_2)
        self.OIP3LowTh.setGeometry(QtCore.QRect(510, 260, 171, 20))
        self.OIP3LowTh.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.OIP3LowTh.setObjectName("OIP3LowTh")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(410, 260, 91, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_63 = QtWidgets.QLabel(self.tab_2)
        self.label_63.setGeometry(QtCore.QRect(410, 230, 91, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.OIP3HighTh = QtWidgets.QLineEdit(self.tab_2)
        self.OIP3HighTh.setGeometry(QtCore.QRect(510, 230, 171, 20))
        self.OIP3HighTh.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.OIP3HighTh.setObjectName("OIP3HighTh")
        self.label_64 = QtWidgets.QLabel(self.tab_2)
        self.label_64.setGeometry(QtCore.QRect(690, 230, 111, 21))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.tab_2)
        self.label_65.setGeometry(QtCore.QRect(690, 260, 111, 21))
        self.label_65.setObjectName("label_65")
        self.label_71 = QtWidgets.QLabel(self.tab_2)
        self.label_71.setGeometry(QtCore.QRect(690, 130, 111, 21))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.tab_2)
        self.label_72.setGeometry(QtCore.QRect(410, 130, 91, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.PoutData = QtWidgets.QLineEdit(self.tab_2)
        self.PoutData.setGeometry(QtCore.QRect(510, 130, 171, 20))
        self.PoutData.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.PoutData.setObjectName("PoutData")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.NFComBox = QtWidgets.QComboBox(self.tab_5)
        self.NFComBox.setGeometry(QtCore.QRect(110, 90, 81, 22))
        self.NFComBox.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFComBox.setObjectName("NFComBox")
        self.NFComFresh = QtWidgets.QPushButton(self.tab_5)
        self.NFComFresh.setGeometry(QtCore.QRect(200, 90, 71, 23))
        self.NFComFresh.setObjectName("NFComFresh")
        self.label_38 = QtWidgets.QLabel(self.tab_5)
        self.label_38.setGeometry(QtCore.QRect(40, 25, 131, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.NFCheckBox = QtWidgets.QCheckBox(self.tab_5)
        self.NFCheckBox.setGeometry(QtCore.QRect(180, 30, 16, 16))
        self.NFCheckBox.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFCheckBox.setText("")
        self.NFCheckBox.setObjectName("NFCheckBox")
        self.NFConComander = QtWidgets.QTextEdit(self.tab_5)
        self.NFConComander.setGeometry(QtCore.QRect(120, 210, 241, 251))
        self.NFConComander.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFConComander.setObjectName("NFConComander")
        self.NFComOpen = QtWidgets.QPushButton(self.tab_5)
        self.NFComOpen.setGeometry(QtCore.QRect(200, 120, 71, 23))
        self.NFComOpen.setObjectName("NFComOpen")
        self.label_39 = QtWidgets.QLabel(self.tab_5)
        self.label_39.setGeometry(QtCore.QRect(50, 210, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_5)
        self.label_40.setGeometry(QtCore.QRect(410, 300, 91, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_5)
        self.label_41.setGeometry(QtCore.QRect(410, 370, 81, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_5)
        self.label_42.setGeometry(QtCore.QRect(410, 420, 81, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.NFSweepTime = QtWidgets.QLineEdit(self.tab_5)
        self.NFSweepTime.setGeometry(QtCore.QRect(490, 120, 101, 20))
        self.NFSweepTime.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFSweepTime.setObjectName("NFSweepTime")
        self.label_43 = QtWidgets.QLabel(self.tab_5)
        self.label_43.setGeometry(QtCore.QRect(410, 120, 81, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_45 = QtWidgets.QLabel(self.tab_5)
        self.label_45.setGeometry(QtCore.QRect(650, 90, 111, 21))
        self.label_45.setObjectName("label_45")
        self.NFStopFreq = QtWidgets.QLineEdit(self.tab_5)
        self.NFStopFreq.setGeometry(QtCore.QRect(590, 90, 51, 20))
        self.NFStopFreq.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFStopFreq.setObjectName("NFStopFreq")
        self.label_46 = QtWidgets.QLabel(self.tab_5)
        self.label_46.setGeometry(QtCore.QRect(550, 80, 31, 31))
        self.label_46.setObjectName("label_46")
        self.NFStartFreq = QtWidgets.QLineEdit(self.tab_5)
        self.NFStartFreq.setGeometry(QtCore.QRect(490, 90, 51, 20))
        self.NFStartFreq.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFStartFreq.setObjectName("NFStartFreq")
        self.label_47 = QtWidgets.QLabel(self.tab_5)
        self.label_47.setGeometry(QtCore.QRect(410, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_5)
        self.label_48.setGeometry(QtCore.QRect(410, 30, 91, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.NFDevRefresh = QtWidgets.QPushButton(self.tab_5)
        self.NFDevRefresh.setGeometry(QtCore.QRect(720, 20, 75, 23))
        self.NFDevRefresh.setObjectName("NFDevRefresh")
        self.NFDev = QtWidgets.QComboBox(self.tab_5)
        self.NFDev.setGeometry(QtCore.QRect(507, 30, 181, 22))
        self.NFDev.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFDev.setObjectName("NFDev")
        self.NFConConfirmAct = QtWidgets.QPushButton(self.tab_5)
        self.NFConConfirmAct.setGeometry(QtCore.QRect(720, 50, 75, 23))
        self.NFConConfirmAct.setObjectName("NFConConfirmAct")
        self.NFENRTab = QtWidgets.QPlainTextEdit(self.tab_5)
        self.NFENRTab.setGeometry(QtCore.QRect(490, 300, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.NFENRTab.setFont(font)
        self.NFENRTab.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFENRTab.setObjectName("NFENRTab")
        self.NFINTab = QtWidgets.QPlainTextEdit(self.tab_5)
        self.NFINTab.setGeometry(QtCore.QRect(490, 370, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.NFINTab.setFont(font)
        self.NFINTab.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFINTab.setPlainText("")
        self.NFINTab.setObjectName("NFINTab")
        self.NFOUTTab = QtWidgets.QPlainTextEdit(self.tab_5)
        self.NFOUTTab.setGeometry(QtCore.QRect(490, 420, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.NFOUTTab.setFont(font)
        self.NFOUTTab.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFOUTTab.setPlainText("")
        self.NFOUTTab.setObjectName("NFOUTTab")
        self.label_49 = QtWidgets.QLabel(self.tab_5)
        self.label_49.setGeometry(QtCore.QRect(650, 120, 111, 21))
        self.label_49.setObjectName("label_49")
        self.label_51 = QtWidgets.QLabel(self.tab_5)
        self.label_51.setGeometry(QtCore.QRect(120, 480, 61, 51))
        self.label_51.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_51.setText("")
        self.label_51.setPixmap(QtGui.QPixmap(":/img/img2.png"))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_5)
        self.label_52.setGeometry(QtCore.QRect(170, 490, 521, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(28)
        font.setUnderline(True)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_52.setObjectName("label_52")
        self.NFSetRefreshAct = QtWidgets.QPushButton(self.tab_5)
        self.NFSetRefreshAct.setGeometry(QtCore.QRect(730, 420, 75, 23))
        self.NFSetRefreshAct.setObjectName("NFSetRefreshAct")
        self.NFSetConfirmAct = QtWidgets.QPushButton(self.tab_5)
        self.NFSetConfirmAct.setGeometry(QtCore.QRect(730, 450, 75, 23))
        self.NFSetConfirmAct.setObjectName("NFSetConfirmAct")
        self.label_60 = QtWidgets.QLabel(self.tab_5)
        self.label_60.setGeometry(QtCore.QRect(410, 230, 71, 20))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.NFTestCondition = QtWidgets.QTextEdit(self.tab_5)
        self.NFTestCondition.setGeometry(QtCore.QRect(490, 220, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(6)
        self.NFTestCondition.setFont(font)
        self.NFTestCondition.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFTestCondition.setObjectName("NFTestCondition")
        self.NFHighTh = QtWidgets.QLineEdit(self.tab_5)
        self.NFHighTh.setGeometry(QtCore.QRect(490, 160, 101, 20))
        self.NFHighTh.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFHighTh.setObjectName("NFHighTh")
        self.label_66 = QtWidgets.QLabel(self.tab_5)
        self.label_66.setGeometry(QtCore.QRect(410, 160, 81, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.NFLowTh = QtWidgets.QLineEdit(self.tab_5)
        self.NFLowTh.setGeometry(QtCore.QRect(490, 190, 101, 20))
        self.NFLowTh.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.NFLowTh.setObjectName("NFLowTh")
        self.label_67 = QtWidgets.QLabel(self.tab_5)
        self.label_67.setGeometry(QtCore.QRect(410, 190, 81, 21))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(12)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.tab_5)
        self.label_68.setGeometry(QtCore.QRect(650, 160, 111, 21))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.tab_5)
        self.label_69.setGeometry(QtCore.QRect(650, 190, 111, 21))
        self.label_69.setObjectName("label_69")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 26))
        self.menubar.setObjectName("menubar")
        self.menuopen = QtWidgets.QMenu(self.menubar)
        self.menuopen.setObjectName("menuopen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuopen.addAction(self.actiontest)
        self.menuopen.addSeparator()
        self.menuopen.addAction(self.actionexit)
        self.menuopen.addSeparator()
        self.menuopen.addSeparator()
        self.menubar.addAction(self.menuopen.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动测试系统客户端v0.3T"))
        self.beginAction.setText(_translate("MainWindow", "开始测试"))
        self.pushButton_2.setText(_translate("MainWindow", "暂停测试"))
        self.cancelTest.setText(_translate("MainWindow", "测试停止"))
        self.label_17.setText(_translate("MainWindow", "产品名称："))
        self.label_23.setText(_translate("MainWindow", "芯片序号："))
        self.label_24.setText(_translate("MainWindow", "测试类别："))
        self.label_25.setText(_translate("MainWindow", "测试温度："))
        self.label_26.setText(_translate("MainWindow", "测试员工："))
        self.label_27.setText(_translate("MainWindow", "测试日期："))
        self.label_34.setText(_translate("MainWindow", "西安博瑞集信电子科技有限公司"))
        self.successDisplay.setText(_translate("MainWindow", "●"))
        self.errDisplay.setText(_translate("MainWindow", "×"))
        self.label_70.setText(_translate("MainWindow", "存放位置："))
        self.selectTxtFile.setText(_translate("MainWindow", "浏览"))
        self.pltBtn.setText(_translate("MainWindow", "绘图"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_74.setText(_translate("MainWindow", "测试用例："))
        self.selectDirBT.setText(_translate("MainWindow", "..."))
        self.uartComFreshBT.setText(_translate("MainWindow", "刷新串口"))
        self.openCurrUartBT.setText(_translate("MainWindow", "打开串口"))
        self.clearDebugBT.setText(_translate("MainWindow", "清除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "开始"))
        self.label_10.setText(_translate("MainWindow", "选择矢网："))
        self.label_11.setText(_translate("MainWindow", "输入功率："))
        self.label_2.setText(_translate("MainWindow", "是否需要SPI配置"))
        self.S_DataDevRefresh.setText(_translate("MainWindow", "刷新设备"))
        self.S_DataConConfirmAct.setText(_translate("MainWindow", "确认连接"))
        self.S_DataSetConfirmAct.setText(_translate("MainWindow", "确认配置"))
        self.S_DataComOpen.setText(_translate("MainWindow", "打开串口"))
        self.S_DataComFresh.setText(_translate("MainWindow", "刷新串口"))
        self.label_28.setText(_translate("MainWindow", "串口指令"))
        self.label_32.setText(_translate("MainWindow", "西安博瑞集信电子科技有限公司"))
        self.S_DataSetRefreshAct.setText(_translate("MainWindow", "重置配置"))
        self.powerInData.setText(_translate("MainWindow", "-25"))
        self.label_36.setText(_translate("MainWindow", "起始频点："))
        self.label_37.setText(_translate("MainWindow", "终止频点："))
        self.label_53.setText(_translate("MainWindow", "单位：（dBm）"))
        self.label_54.setText(_translate("MainWindow", "单位：（Hz）"))
        self.label_55.setText(_translate("MainWindow", "单位：（Hz）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "S参数配置"))
        self.label_8.setText(_translate("MainWindow", "选择矢网："))
        self.label_12.setText(_translate("MainWindow", "测试频点"))
        self.P1TestCondition.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">10000000,100000000,20000000,300000000,400000000,500000000,600000000,700000000,800000000,900000000,1000000000</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "平均数："))
        self.label_15.setText(_translate("MainWindow", "终止功率："))
        self.P1AverData.setText(_translate("MainWindow", "10"))
        self.P1PowerStopData.setText(_translate("MainWindow", "0"))
        self.P1ComOpen.setText(_translate("MainWindow", "打开串口"))
        self.label_5.setText(_translate("MainWindow", "是否需要SPI配置"))
        self.label_20.setText(_translate("MainWindow", "串口指令"))
        self.P1ComFresh.setText(_translate("MainWindow", "刷新串口"))
        self.P1ConConfirmAct.setText(_translate("MainWindow", "确认连接"))
        self.P1DevRefresh.setText(_translate("MainWindow", "刷新设备"))
        self.P1SetConfirmAct.setText(_translate("MainWindow", "确认配置"))
        self.label_30.setText(_translate("MainWindow", "西安博瑞集信电子科技有限公司"))
        self.P1SetRefreshAct.setText(_translate("MainWindow", "重置配置"))
        self.label_58.setText(_translate("MainWindow", "单位：（dBm）"))
        self.label_59.setText(_translate("MainWindow", "单位：（个）"))
        self.label_44.setText(_translate("MainWindow", "P1下限："))
        self.label_50.setText(_translate("MainWindow", "P1上限："))
        self.P1HighTh.setText(_translate("MainWindow", "40"))
        self.P1LowTh.setText(_translate("MainWindow", "0"))
        self.label_61.setText(_translate("MainWindow", "单位：（dBm）"))
        self.label_62.setText(_translate("MainWindow", "单位：（dBm）"))
        self.P1LossValue.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">0.14,0.16,0.17,0.35,0.60,0.68,0.90,1.12,1.67,1.72,1.83</span></p></body></html>"))
        self.label_73.setText(_translate("MainWindow", "标准线损:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", " P1配置 "))
        self.label_3.setText(_translate("MainWindow", "选择频谱仪:"))
        self.label_4.setText(_translate("MainWindow", "信号源:"))
        self.label_13.setText(_translate("MainWindow", "测试频点:"))
        self.OIP3TestCondition.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">10000000,100000000,20000000,300000000,400000000,500000000,600000000,700000000,800000000,900000000,1000000000</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "标准线损:"))
        self.OIP3LossValue.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">0.14,0.16,0.17,0.35,0.60,0.68,0.90,1.12,1.67,1.72</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "功率保护:"))
        self.label_16.setText(_translate("MainWindow", "扫描带宽:"))
        self.sweepBW.setText(_translate("MainWindow", "10000000"))
        self.signalProtect.setText(_translate("MainWindow", "5"))
        self.OIP3ComOpen.setText(_translate("MainWindow", "打开串口"))
        self.OIP3ComFresh.setText(_translate("MainWindow", "刷新串口"))
        self.label_21.setText(_translate("MainWindow", "是否需要SPI配置"))
        self.label_22.setText(_translate("MainWindow", "串口指令"))
        self.conConfirmAct1.setText(_translate("MainWindow", "确认连接"))
        self.OIP3DevRefresh.setText(_translate("MainWindow", "刷新设备"))
        self.conConfirmAct2.setText(_translate("MainWindow", "确认连接"))
        self.setConfirmAct.setText(_translate("MainWindow", "确认配置"))
        self.setRefreshAct.setText(_translate("MainWindow", "重置配置"))
        self.label_29.setText(_translate("MainWindow", "西安博瑞集信电子科技有限公司"))
        self.label_56.setText(_translate("MainWindow", "单位：（Hz）"))
        self.label_57.setText(_translate("MainWindow", "单位：（dBm）"))
        self.OIP3LowTh.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "OIP3下限："))
        self.label_63.setText(_translate("MainWindow", "OIP3上限："))
        self.OIP3HighTh.setText(_translate("MainWindow", "50"))
        self.label_64.setText(_translate("MainWindow", "单位：（dBm）"))
        self.label_65.setText(_translate("MainWindow", "单位：（dBm）"))
        self.label_71.setText(_translate("MainWindow", "单位：（dBm）"))
        self.label_72.setText(_translate("MainWindow", "输出功率："))
        self.PoutData.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "OIP3配置"))
        self.NFComFresh.setText(_translate("MainWindow", "刷新串口"))
        self.label_38.setText(_translate("MainWindow", "是否需要SPI配置"))
        self.NFComOpen.setText(_translate("MainWindow", "打开串口"))
        self.label_39.setText(_translate("MainWindow", "串口指令"))
        self.label_40.setText(_translate("MainWindow", "ENR_Tab:"))
        self.label_41.setText(_translate("MainWindow", "IN_Tab:"))
        self.label_42.setText(_translate("MainWindow", "OUT_Tab:"))
        self.NFSweepTime.setText(_translate("MainWindow", "0.1"))
        self.label_43.setText(_translate("MainWindow", "扫描间隔："))
        self.label_45.setText(_translate("MainWindow", "单位：（MHz）"))
        self.NFStopFreq.setText(_translate("MainWindow", "6000"))
        self.label_46.setText(_translate("MainWindow", "_____"))
        self.NFStartFreq.setText(_translate("MainWindow", "10"))
        self.label_47.setText(_translate("MainWindow", "频率选择："))
        self.label_48.setText(_translate("MainWindow", "选择频谱仪:"))
        self.NFDevRefresh.setText(_translate("MainWindow", "刷新设备"))
        self.NFConConfirmAct.setText(_translate("MainWindow", "确认连接"))
        self.NFENRTab.setPlainText(_translate("MainWindow", "10MHz,15.37,100MHz,15.38,1000MHz,15.27,2000MHz,15.05,3000MHz,14.97,4000MHz,14.91,5000MHz,14.91,6000MHz,14.86,7000MHz,14.87,8000MHz,14.91,9000MHz,15.03,10000MHz,15.02,11000MHz,15.03,12000MHz,15.07,13000MHz,15.01,14000MHz,15.11,15000MHz,15.10,16000MHz,15.06,17000MHz,15.30,18000MHz,15.41"))
        self.label_49.setText(_translate("MainWindow", "单位：（秒）"))
        self.label_52.setText(_translate("MainWindow", "西安博瑞集信电子科技有限公司"))
        self.NFSetRefreshAct.setText(_translate("MainWindow", "重置配置"))
        self.NFSetConfirmAct.setText(_translate("MainWindow", "确认配置"))
        self.label_60.setText(_translate("MainWindow", "测试频点:"))
        self.NFTestCondition.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:6pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'黑体\'; font-size:8pt;\">10MHz,100MHz,2000MHz,2500MHz,3000MHz,3500MHz,4000MHz,4500MHz,5000MHz,5500MHz,6000MHz</span></p></body></html>"))
        self.NFHighTh.setText(_translate("MainWindow", "10"))
        self.label_66.setText(_translate("MainWindow", "NF上限："))
        self.NFLowTh.setText(_translate("MainWindow", "0"))
        self.label_67.setText(_translate("MainWindow", "NF下限："))
        self.label_68.setText(_translate("MainWindow", "单位：（dBm）"))
        self.label_69.setText(_translate("MainWindow", "单位：（dBm）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", " NF配置 "))
        self.menuopen.setTitle(_translate("MainWindow", "设置"))
        self.actiontest.setText(_translate("MainWindow", "测试设置"))
        self.actionexit.setText(_translate("MainWindow", "退出"))

import my1050imgFolder
