# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 833)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, -1, 1081, 801))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.beginAction = QtWidgets.QPushButton(self.tab)
        self.beginAction.setGeometry(QtCore.QRect(50, 500, 81, 23))
        self.beginAction.setObjectName("beginAction")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 560, 81, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.cancelTest = QtWidgets.QPushButton(self.tab)
        self.cancelTest.setGeometry(QtCore.QRect(50, 620, 81, 23))
        self.cancelTest.setObjectName("cancelTest")
        self.testType = QtWidgets.QComboBox(self.tab)
        self.testType.setGeometry(QtCore.QRect(130, 140, 111, 22))
        self.testType.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.testType.setObjectName("testType")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(50, 80, 71, 21))
        self.label_17.setObjectName("label_17")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(50, 110, 71, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(50, 140, 71, 21))
        self.label_24.setObjectName("label_24")
        self.testTemp = QtWidgets.QComboBox(self.tab)
        self.testTemp.setGeometry(QtCore.QRect(130, 170, 111, 22))
        self.testTemp.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.testTemp.setObjectName("testTemp")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(50, 170, 71, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(50, 200, 71, 21))
        self.label_26.setObjectName("label_26")
        self.chipName = QtWidgets.QLineEdit(self.tab)
        self.chipName.setGeometry(QtCore.QRect(130, 80, 111, 20))
        self.chipName.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.chipName.setObjectName("chipName")
        self.chipNum = QtWidgets.QLineEdit(self.tab)
        self.chipNum.setGeometry(QtCore.QRect(130, 110, 111, 20))
        self.chipNum.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.chipNum.setObjectName("chipNum")
        self.testerNum = QtWidgets.QLineEdit(self.tab)
        self.testerNum.setGeometry(QtCore.QRect(130, 200, 111, 20))
        self.testerNum.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.testerNum.setObjectName("testerNum")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(50, 230, 71, 21))
        self.label_27.setObjectName("label_27")
        self.testDate = QtWidgets.QDateEdit(self.tab)
        self.testDate.setGeometry(QtCore.QRect(130, 230, 111, 22))
        self.testDate.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.testDate.setObjectName("testDate")
        self.debugView = QtWidgets.QPlainTextEdit(self.tab)
        self.debugView.setGeometry(QtCore.QRect(340, 50, 641, 601))
        self.debugView.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.debugView.setObjectName("debugView")
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(230, 690, 691, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(28)
        font.setUnderline(True)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(180, 680, 61, 51))
        self.label_35.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap(":/img/img2.png"))
        self.label_35.setObjectName("label_35")
        self.successDisplay = QtWidgets.QLabel(self.tab)
        self.successDisplay.setGeometry(QtCore.QRect(1020, 50, 31, 31))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(20)
        self.successDisplay.setFont(font)
        self.successDisplay.setStyleSheet("color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(0, 255, 78, 255));")
        self.successDisplay.setObjectName("successDisplay")
        self.errDisplay = QtWidgets.QLabel(self.tab)
        self.errDisplay.setGeometry(QtCore.QRect(1020, 40, 31, 41))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(22)
        self.errDisplay.setFont(font)
        self.errDisplay.setStyleSheet("color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 0, 0, 255));")
        self.errDisplay.setObjectName("errDisplay")
        self.stateDisplay = QtWidgets.QLabel(self.tab)
        self.stateDisplay.setGeometry(QtCore.QRect(750, 50, 51, 31))
        self.stateDisplay.setText("")
        self.stateDisplay.setObjectName("stateDisplay")
        self.dataLocation = QtWidgets.QComboBox(self.tab)
        self.dataLocation.setGeometry(QtCore.QRect(130, 260, 111, 22))
        self.dataLocation.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.dataLocation.setObjectName("dataLocation")
        self.label_70 = QtWidgets.QLabel(self.tab)
        self.label_70.setGeometry(QtCore.QRect(50, 260, 71, 21))
        self.label_70.setObjectName("label_70")
        self.fileDir = QtWidgets.QLineEdit(self.tab)
        self.fileDir.setGeometry(QtCore.QRect(50, 290, 121, 20))
        self.fileDir.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.fileDir.setObjectName("fileDir")
        self.selectTxtFile = QtWidgets.QPushButton(self.tab)
        self.selectTxtFile.setGeometry(QtCore.QRect(180, 290, 41, 23))
        self.selectTxtFile.setObjectName("selectTxtFile")
        self.pltBtn = QtWidgets.QPushButton(self.tab)
        self.pltBtn.setGeometry(QtCore.QRect(230, 290, 41, 23))
        self.pltBtn.setObjectName("pltBtn")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(900, 710, 72, 15))
        self.label.setObjectName("label")
        self.label_74 = QtWidgets.QLabel(self.tab)
        self.label_74.setGeometry(QtCore.QRect(50, 50, 71, 21))
        self.label_74.setObjectName("label_74")
        self.iniFileDir = QtWidgets.QLineEdit(self.tab)
        self.iniFileDir.setGeometry(QtCore.QRect(130, 51, 111, 20))
        self.iniFileDir.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.iniFileDir.setObjectName("iniFileDir")
        self.selectDirBT = QtWidgets.QPushButton(self.tab)
        self.selectDirBT.setGeometry(QtCore.QRect(250, 52, 41, 21))
        self.selectDirBT.setObjectName("selectDirBT")
        self.uartComBox = QtWidgets.QComboBox(self.tab)
        self.uartComBox.setGeometry(QtCore.QRect(50, 340, 101, 22))
        self.uartComBox.setStyleSheet("border:2px solid rgb(0,0,0);\n"
"background-color: qlineargradient(spread:pad, x1:0.347, y1:0.426455, x2:1, y2:0, stop:1 rgba(255, 255, 245, 255));")
        self.uartComBox.setObjectName("uartComBox")
        self.uartComFreshBT = QtWidgets.QPushButton(self.tab)
        self.uartComFreshBT.setGeometry(QtCore.QRect(160, 340, 81, 23))
        self.uartComFreshBT.setObjectName("uartComFreshBT")
        self.openCurrUartBT = QtWidgets.QPushButton(self.tab)
        self.openCurrUartBT.setGeometry(QtCore.QRect(250, 340, 81, 23))
        self.openCurrUartBT.setObjectName("openCurrUartBT")
        self.clearDebugBT = QtWidgets.QPushButton(self.tab)
        self.clearDebugBT.setGeometry(QtCore.QRect(990, 630, 71, 23))
        self.clearDebugBT.setObjectName("clearDebugBT")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(210, 610, 691, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(28)
        font.setUnderline(True)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(160, 600, 61, 51))
        self.label_33.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap(":/img/img2.png"))
        self.label_33.setObjectName("label_33")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 26))
        self.menubar.setObjectName("menubar")
        self.menuopen = QtWidgets.QMenu(self.menubar)
        self.menuopen.setObjectName("menuopen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuopen.addAction(self.actiontest)
        self.menuopen.addSeparator()
        self.menuopen.addAction(self.actionexit)
        self.menuopen.addSeparator()
        self.menuopen.addSeparator()
        self.menubar.addAction(self.menuopen.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动测试系统客户端v0.3T"))
        self.beginAction.setText(_translate("MainWindow", "开始测试"))
        self.pushButton_2.setText(_translate("MainWindow", "暂停测试"))
        self.cancelTest.setText(_translate("MainWindow", "测试停止"))
        self.label_17.setText(_translate("MainWindow", "产品名称："))
        self.label_23.setText(_translate("MainWindow", "芯片序号："))
        self.label_24.setText(_translate("MainWindow", "测试类别："))
        self.label_25.setText(_translate("MainWindow", "测试温度："))
        self.label_26.setText(_translate("MainWindow", "测试员工："))
        self.label_27.setText(_translate("MainWindow", "测试日期："))
        self.label_34.setText(_translate("MainWindow", "西安博瑞集信电子科技有限公司"))
        self.successDisplay.setText(_translate("MainWindow", "●"))
        self.errDisplay.setText(_translate("MainWindow", "×"))
        self.label_70.setText(_translate("MainWindow", "存放位置："))
        self.selectTxtFile.setText(_translate("MainWindow", "浏览"))
        self.pltBtn.setText(_translate("MainWindow", "绘图"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_74.setText(_translate("MainWindow", "测试用例："))
        self.selectDirBT.setText(_translate("MainWindow", "..."))
        self.uartComFreshBT.setText(_translate("MainWindow", "刷新串口"))
        self.openCurrUartBT.setText(_translate("MainWindow", "打开串口"))
        self.clearDebugBT.setText(_translate("MainWindow", "清除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "开始"))
        self.label_32.setText(_translate("MainWindow", "西安博瑞集信电子科技有限公司"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "预留页面"))
        self.menuopen.setTitle(_translate("MainWindow", "设置"))
        self.actiontest.setText(_translate("MainWindow", "测试设置"))
        self.actionexit.setText(_translate("MainWindow", "退出"))

import my1050imgFolder
